# Generated by Django 4.1.2 on 2022-10-30 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('easypush', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apptokenplatformmodel',
            name='app_name',
            field=models.CharField(default='', max_length=100, verbose_name='应用名称'),
        ),
    ]
