# Generated by Django 4.1.2 on 2022-11-09 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('easypush', '0002_remove_appmessagemodel_media_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appmsgpushrecordmodel',
            name='msg_uid',
            field=models.CharField(blank=True, default='', max_length=150, unique=True, verbose_name='消息唯一id'),
        ),
        migrations.AlterField(
            model_name='appmsgpushrecordmodel',
            name='request_id',
            field=models.CharField(blank=True, default='', max_length=150, verbose_name='钉钉推送的请求ID'),
        ),
        migrations.AlterField(
            model_name='appmsgpushrecordmodel',
            name='task_id',
            field=models.CharField(blank=True, db_index=True, default='', max_length=150, verbose_name='钉钉创建的异步发送任务ID'),
        ),
        migrations.AlterField(
            model_name='apptokenplatformmodel',
            name='agent_id',
            field=models.IntegerField(default=0, verbose_name='AppId'),
        ),
        migrations.AlterField(
            model_name='apptokenplatformmodel',
            name='app_secret',
            field=models.CharField(default='', max_length=300, verbose_name='应用 appSecret'),
        ),
        migrations.AlterField(
            model_name='apptokenplatformmodel',
            name='platform_type',
            field=models.CharField(choices=[('sms', '短信'), ('email', '邮件'), ('feishu', '飞书'), ('ding_talk', '钉钉'), ('qy_weixin', '企业微信')], default='', max_length=50, verbose_name='平台类型'),
        ),
    ]
