# Generated by Django 4.1.2 on 2022-11-10 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('easypush', '0003_alter_appmsgpushrecordmodel_msg_uid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appmediastoragemodel',
            name='expire_time',
            field=models.BigIntegerField(default=7200, verbose_name='媒体过期时间'),
        ),
    ]
