# Generated by Django 4.1.2 on 2022-11-11 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('easypush', '0004_appmediastoragemodel_expire_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appmediastoragemodel',
            name='expire_time',
            field=models.DateTimeField(blank=True, default='1979-01-01 00:00:00', verbose_name='媒体过期时间'),
        ),
        migrations.AlterField(
            model_name='apptokenplatformmodel',
            name='expire_time',
            field=models.DateTimeField(blank=True, default='1979-01-01 00:00:00', verbose_name='token过期时间'),
        ),
    ]
