# Generated by Django 4.0.8 on 2022-12-29 18:24

from django.db import migrations, models
import django.db.models.deletion
import easypush.core.db.base


class Migration(migrations.Migration):

    dependencies = [
        ('easypush', '0007_alter_apptokenplatformmodel_agent_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CeleryTaskResultAlertModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creator', models.CharField(default=easypush.core.db.base.AutoExecutor(), max_length=200, verbose_name='创建人')),
                ('modifier', models.CharField(default=easypush.core.db.base.AutoExecutor(), max_length=200, verbose_name='创建人')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_del', models.BooleanField(default=False, verbose_name='是否删除')),
                ('task_name', models.CharField(blank=True, max_length=500, unique=True, verbose_name='任务名')),
                ('msg_type', models.CharField(blank=True, choices=[('text', '文本消息'), ('image', '图片消息'), ('voice', '语音消息'), ('file', '文件消息'), ('news', '图文消息'), ('mpnews', '图文消息'), ('markdown', 'markdown 消息'), ('textcard', '文本卡片消息'), ('miniprogram_notice', '小程序通知消息'), ('template_card', '模板卡片消息'), ('text', '文本消息'), ('image', '图片消息'), ('voice', '语音消息'), ('file', '文件消息'), ('link', '链接消息'), ('oa', 'OA 消息'), ('markdown', 'markdown 消息'), ('action_card', 'action_card 消息'), ('single_action_card', 'action_card 消息'), ('btn_action_card', 'action_card 消息')], default='', max_length=50, verbose_name='消息类型')),
                ('msg_body', models.CharField(blank=True, default='', max_length=2000, verbose_name='消息JSON数据')),
                ('platform_type', models.CharField(choices=[('sms', '短信'), ('email', '邮件'), ('feishu', '飞书'), ('ding_talk', '钉钉'), ('qy_weixin', '企业微信')], default='', max_length=100, verbose_name='平台类型')),
                ('remark', models.CharField(blank=True, default='', max_length=200, verbose_name='说明')),
                ('app', models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='easypush.apptokenplatformmodel', verbose_name='应用id')),
            ],
            options={
                'db_table': 'easypush_celery_task_result_alert_msg',
            },
        ),
    ]
